export const exploreWorlds = [
  {
    id: 'world-1',
    imgUrl: '/translation1.jpg',
    title: 'Translation',
  },
  {
    id: 'world-2',
    imgUrl: '/translation2.jpg',
    title: 'Localization',
  },
  {
    id: 'world-3',
    imgUrl: '/translation5.jpg',
    title: 'Desktop Publishing',
  },
  {
    id: 'world-4',
    imgUrl: '/translation6.jpg',
    title: 'Voiceovers',
  },
  {
    id: 'world-5',
    imgUrl: '/translation7.jpg',
    title: 'Transcription',
  },
];

export const startingFeatures = [
  'We examine the source files, and we share a precise delivery schedule.',
  "As agreed, we work on the files, communicate our progress, and solicit client's opinions",
  'Smooth Delivery after analyzing feedback and completing the QA.',
];

export const newFeatures = [
  {
    imgUrl: '/vrpano.svg',
    title: 'A new world',
    subtitle:
        'we have the latest update with new world for you to try never mind',
  },
  {
    imgUrl: '/headset.svg',
    title: 'More realistic',
    subtitle:
        'In the latest update, your eyes are narrow, making the world more realistic than ever',
  },
];

export const insights = [
  {
    imgUrl: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1617&q=80',
    title: 'How a Bad Translation Started A War…',
    subtitle:
        'The Battle of Adwa was a major conflict in the late 19th century that pitted the Ethiopian Empire against the Kingdom of Italy.',
  },
  {
    imgUrl: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
    title: 'Time to invest in translation so your business can grow in the digital world',
    subtitle:
        'With advent of cyber technology, no doubt you have noticed we are entering to multi-ethnic global lucrative market.',
  },
  {
    imgUrl: 'https://images.unsplash.com/photo-1599045118108-bf9954418b76?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
    title: 'Things you should know about Medical Paper Translation',
    subtitle:
        'Medical translation is a translation service that helps people translate their medical documents into other languages. For example, Clinical trial results, pharmaceutical regulations, medical reports, and live interpretation.',
  },
];

export const socials = [
  {
    name: 'twitter',
    url: '/twitter.svg',
  },
  {
    name: 'linkedin',
    url: '/linkedin.svg',
  },
  {
    name: 'instagram',
    url: '/instagram.svg',
  },
  {
    name: 'facebook',
    url: '/facebook.svg',
  },
];

export const ourServices = [
  {
    imgUrl: '/language.svg',
    title: 'Document Translation',
    subtitle:
        ' Through a rigorous recruitment process and ongoing training, our network of linguists, reviewers, and subject matter experts (SME) ensure that we have the capacity to handle any volume and speed. ',
  },
  {
    imgUrl: '/interpreter.svg',
    title: 'Interpretation',
    subtitle:
        'We provide certified, professional interpreters with technical and subject matter expertise, allowing you to communicate effectively in more than 250 languages.',
  },
  {
    imgUrl: '/localization.svg',
    title: 'Localization',
    subtitle:
        'Your localization business process is fully managed by our resources specialized in localization as well as other skills such as project management, project engineering and desktop publishing (DTP). ',
  },
  {
    imgUrl: '/certificate.svg',
    title: 'Localization',
    subtitle:
        'Your localization business process is fully managed by our resources specialized in localization as well as other skills such as project management, project engineering and desktop publishing (DTP). ',
  },
  {
    imgUrl: '/desktop.svg',
    title: 'Desktop Publishing',
    subtitle:
        'Enjoy Ethiostars cost-effective DTP services and start reaching your target audience in the Middle East and Africa in no time.  we may use Adobe InDesign, Adobe PageMaker and other tools.',
  },
  {
    imgUrl: '/copywritting.svg',
    title: 'Copy Writing',
    subtitle:
        'Copywriting is the act or the occupation of writing text for advertising or other forms of marketing. we will help you in your strive to increase brand awareness and global reach',
  },
  {
    imgUrl: '/magnifying-glass.svg',
    title: 'Proofreading',
    subtitle:
        'Our proofreaders help you to find out if anything goes wrong during typesetting by the printing press or your reviewer and you skipped during your review before sending the document for translation.  ',
  },
  {
    imgUrl: '/medical.svg',
    title: 'Medical Translation',
    subtitle:
        'we provide medical translation by specialist medical translators. We set high criteria, ensuring that our translators have expert skills in the subject, and provide a first-class translation of your material. ',
  },
];

export const allLanguages = [
  { name: 'Spanish (ES)', group: 1 },
  { name: 'Spanish (LATAM)', group: 1 },
  { name: 'US English', group: 1 },
  { name: 'English UK', group: 1 },
  { name: 'Português BR', group: 1 },
  { name: 'Português PT', group: 1 },
  { name: 'Amharic', group: 1 },
  { name: 'French', group: 2 },
  { name: 'French Canadian', group: 2 },
  { name: 'Italian', group: 2 },
  { name: 'German', group: 2 },
  { name: 'Tigrinya', group: 2 },
  { name: 'Arabic', group: 3 },
  { name: 'Chinese (Mandarin Simplified)', group: 3 },
  { name: 'Danish', group: 3 },
  { name: 'Finnish', group: 3 },
  { name: 'Hebrew', group: 3 },
  { name: 'Dutch', group: 3 },
  { name: 'Icelandic', group: 3 },
  { name: 'Japanese', group: 3 },
  { name: 'Norwegian', group: 3 },
  { name: 'Oromo', group: 3 },
  { name: 'Russian', group: 3 },
  { name: 'Swedish', group: 3 },
  { name: 'Czech', group: 3 },
  { name: 'Turkish', group: 3 },
  { name: 'Polish', group: 3 },
  { name: 'Greek', group: 3 },
  { name: 'Afar', group: 4 },
  { name: 'Afrikaans', group: 4 },
  { name: 'Akan', group: 4 },
  { name: 'Albanian', group: 4 },
  { name: 'Agnwak', group: 4 },
  { name: 'Armenian', group: 4 },
  { name: 'Assamese', group: 4 },
  { name: 'Assyrian', group: 4 },
  { name: 'Azeri', group: 4 },
  { name: 'Bambara', group: 4 },
  { name: 'Basque', group: 4 },
  { name: 'Bashkir', group: 4 },
  { name: 'Bengale', group: 4 },
  { name: 'Belarus - Russian', group: 4 },
  { name: 'blen', group: 4 },
  { name: 'Burmese', group: 4 },
  { name: 'Bosnian', group: 4 },
  { name: 'Bravanese', group: 4 },
  { name: 'Bulgarian', group: 4 },
  { name: 'Bhutanese', group: 4 },
  { name: 'Cambodian', group: 4 },
  { name: 'Kananese', group: 4 },
  { name: 'Canjobal', group: 4 },
  { name: 'Cantonese', group: 4 },
  { name: 'Catalan', group: 4 },
  { name: 'Kashmir', group: 4 },
  { name: 'Kazakh', group: 4 },
  { name: 'Cebuano', group: 4 },
  { name: 'Chaldean', group: 4 },
  { name: 'Chamorro', group: 4 },
  { name: 'Chaozhou', group: 4 },
  { name: 'Chavacano', group: 4 },
  { name: 'Chinese (Mandarin Traditional)', group: 4 },
  { name: 'Chona', group: 4 },
  { name: 'Chuquês', group: 4 },
  { name: 'Sinhalese', group: 4 },
  { name: 'Korean', group: 4 },
  { name: 'Cree', group: 4 },
  { name: 'Croatian', group: 4 },
  { name: 'Kurdo', group: 4 },
  { name: 'Curmânji', group: 4 },
  { name: 'Dakota', group: 4 },
  { name: 'Dari', group: 4 },
  { name: 'Dinka', group: 4 },
  { name: 'Dioula', group: 4 },
  { name: 'Slovak', group: 4 },
  { name: 'Slovenian', group: 4 },
  { name: 'Estonian', group: 4 },
  { name: 'Ewe', group: 4 },
  { name: 'Fanti', group: 4 },
  { name: 'Faroese', group: 4 },
  { name: 'Farsi', group: 4 },
  { name: 'Flamengo', group: 4 },
  { name: 'Frisian', group: 4 },
  { name: 'Fujian', group: 4 },
  { name: 'Fujianese', group: 4 },
  { name: 'Fula', group: 4 },
  { name: 'Fulani', group: 4 },
  { name: 'Fuzhou', group: 4 },
  { name: 'Gaélico', group: 4 },
  { name: 'Galego', group: 4 },
  { name: 'Galês', group: 4 },
  { name: 'Ganda', group: 4 },
  { name: 'Georgiano', group: 4 },
  { name: 'Gorani', group: 4 },
  { name: 'Guanxi', group: 4 },
  { name: 'Gujarati', group: 4 },
  { name: 'Hacá', group: 4 },
  { name: 'Haitiano', group: 4 },
  { name: 'Hassaniya', group: 4 },
  { name: 'Hauçá', group: 4 },
  { name: 'Hiligaynon', group: 4 },
  { name: 'Hindi', group: 4 },
  { name: 'Hindi fijiano', group: 4 },
  { name: 'Hmong', group: 4 },
  { name: 'Húngaro', group: 4 },
  { name: 'Ibanag', group: 4 },
  { name: 'Igbo', group: 4 },
  { name: 'Iídiche', group: 4 },
  { name: 'Ilocano', group: 4 },
  { name: 'Ilonggo', group: 4 },
  { name: 'Indiano', group: 4 },
  { name: 'Indonésio', group: 4 },
  { name: 'Inuktitut', group: 4 },
  { name: 'Iorubá', group: 4 },
  { name: 'Irlandês', group: 4 },
  { name: 'Jakartanese', group: 4 },
  { name: 'Javanês', group: 4 },
  { name: 'Karen', group: 4 },
  { name: 'Khalkha', group: 4 },
  { name: 'Khmer', group: 4 },
  { name: 'Kikuyu', group: 4 },
  { name: 'Kirundi', group: 4 },
  { name: 'Kosovo', group: 4 },
  { name: 'Kotokoli', group: 4 },
  { name: 'Krio', group: 4 },
  { name: 'Lakota', group: 4 },
  { name: 'Laociano', group: 4 },
  { name: 'Latim', group: 4 },
  { name: 'Letão', group: 4 },
  { name: 'Lingala', group: 4 },
  { name: 'Língua de sinais americana', group: 4 },
  { name: 'Lituano', group: 4 },
  { name: 'Luganda', group: 4 },
  { name: 'Luo', group: 4 },
  { name: 'Lusoga', group: 4 },
  { name: 'Luxemburguês', group: 4 },
  { name: 'Maay', group: 4 },
  { name: 'Macedônio', group: 4 },
  { name: 'Malaiala', group: 4 },
  { name: 'Malaio', group: 4 },
  { name: 'Maldivense', group: 4 },
  { name: 'Malgaxe', group: 4 },
  { name: 'Maltês', group: 4 },
  { name: 'Mandarim Tradicional', group: 4 },
  { name: 'Mandinga', group: 4 },
  { name: 'Mandinka', group: 4 },
  { name: 'Maori', group: 4 },
  { name: 'Marata', group: 4 },
  { name: 'Marshalês', group: 4 },
  { name: 'Mien', group: 4 },
  { name: 'Mirpuri', group: 4 },
  { name: 'Mixteco', group: 4 },
  { name: 'Moldovan', group: 4 },
  { name: 'Mongol', group: 4 },
  { name: 'Napolitano', group: 4 },
  { name: 'Navajo', group: 4 },
  { name: 'Nepali', group: 4 },
  { name: 'Nianja', group: 4 },
  { name: 'Nuer', group: 4 },
  { name: 'Ojíbua', group: 4 },
  { name: 'Oriá', group: 4 },
  { name: 'Osseta', group: 4 },
  { name: 'Pachto', group: 4 },
  { name: 'Pahari', group: 4 },
  { name: 'Pampangan', group: 4 },
  { name: 'Patoá', group: 4 },
  { name: 'Pothwari', group: 4 },
  { name: 'Pulaar', group: 4 },
  { name: 'Punjabi', group: 4 },
  { name: 'Putian', group: 4 },
  { name: 'Quechua', group: 4 },
  { name: 'Quiniaruanda', group: 4 },
  { name: 'Quirguiz', group: 4 },
  { name: 'Romanche', group: 4 },
  { name: 'Romani', group: 4 },
  { name: 'Romeno', group: 4 },
  { name: 'Rundi', group: 4 },
  { name: 'Samoano', group: 4 },
  { name: 'Sango', group: 4 },
  { name: 'Sânscrito', group: 4 },
  { name: 'Sérvio', group: 4 },
  { name: 'Sichuan', group: 4 },
  { name: 'Siciliano', group: 4 },
  { name: 'Sindi', group: 4 },
  { name: 'Somali', group: 4 },
  { name: 'Soninquê', group: 4 },
  { name: 'Sorâni', group: 4 },
  { name: 'Soto do sul', group: 4 },
  { name: 'Suaíle', group: 4 },
  { name: 'Suázi / suazilandês', group: 4 },
  { name: 'Sundanês', group: 4 },
  { name: 'Susu', group: 4 },
  { name: 'Sylheti', group: 4 },
  { name: 'Tadjique', group: 4 },
  { name: 'Tagalog', group: 4 },
  { name: 'Tailandês', group: 4 },
  { name: 'Taiwanês', group: 4 },
  { name: 'Tâmil', group: 4 },
  { name: 'Telugu', group: 4 },
  { name: 'Tibetano', group: 4 },
  { name: 'Tigre', group: 4 },
  { name: 'Tonga', group: 4 },
  { name: 'Tshiluba', group: 4 },
  { name: 'Tsonga', group: 4 },
  { name: 'Tswana', group: 4 },
  { name: 'Turcomeno', group: 4 },
  { name: 'Ucraniano', group: 4 },
  { name: 'Uigur', group: 4 },
  { name: 'Uolofe', group: 4 },
  { name: 'Urdu', group: 4 },
  { name: 'Uzbeque', group: 4 },
  { name: 'Venda', group: 4 },
  { name: 'Vietnamita', group: 4 },
  { name: 'Visayan', group: 4 },
  { name: 'Xangainês', group: 4 },
  { name: 'Xhosa', group: 4 },
  { name: 'Yao', group: 4 },
  { name: 'Yupik', group: 4 },
  { name: 'Zulu', group: 4 },
];

export const wordServicesGroups = [
  // GRUPO 1
  {
    humanTranslation: {
      wordsPerDay: 4000,
      baseDays: 1,
      baseCost: 0.05,
      thresholdCost: 0.07,
    },
    machineTranslation: {
      wordsPerDay: 8000,
      baseDays: 1,
      baseCost: 0.15,
      thresholdCost: 0.14,
    },
  },
  // GRUPO 2
  {
    humanTranslation: {
      wordsPerDay: 3000,
      baseDays: 1,
      baseCost: 0.07,
      thresholdCost: 0.06,
    },
    machineTranslation: {
      wordsPerDay: 8000,
      baseDays: 1,
      baseCost: 0.15,
      thresholdCost: 0.14,
    },
  },
  // GRUPO 3
  {
    humanTranslation: {
      wordsPerDay: 2000,
      baseDays: 2,
      baseCost: 0.09,
      thresholdCost: 0.09,
    },
    machineTranslation: {
      wordsPerDay: 8000,
      baseDays: 1,
      baseCost: 0.15,
      thresholdCost: 0.14,
    },
  },
  // GRUPO 4
  {
    humanTranslation: {
      wordsPerDay: 4000,
      baseDays: 1,
      baseCost: 0.12,
      thresholdCost: 0.11,
    },
    machineTranslation: {
      wordsPerDay: 8000,
      baseDays: 1,
      baseCost: 0.15,
      thresholdCost: 0.14,
    },
  },
];
export const LANGUAGE_PRICES = {
  'Spanish (ES)': 0.09,
  'Spanish (LATAM)': 0.09,
  'US English': 0.09,
  'English UK': 0.09,
  'Português BR': 0.09,
  'Português PT': 0.09,
  Amharic: 0.08,
  French: 0.09,
  'French Canadian': 0.09,
  Italian: 0.09,
  German: 0.09,
  Arabic: 0.09,
  'Chinese (Mandarin Simplified)': 0.09,
  Danish: 0.09,
  Finnish: 0.09,
  Hebrew: 0.09,
  Dutch: 0.09,
  Icelandic: 0.09,
  Japanese: 0.09,
  Norwegian: 0.09,
  Russian: 0.09,
  Swedish: 0.09,
  Czech: 0.09,
  Turkish: 0.09,
  Polish: 0.09,
  Greek: 0.09,
  Afar: 0.09,
  Afrikaans: 0.09,
  Akan: 0.09,
  Albanian: 0.09,
  Agnwak: 0.12,
  Armenian: 0.09,
  Assamese: 0.09,
  Assyrian: 0.09,
  Azeri: 0.09,
  Bambara: 0.09,
  Basque: 0.09,
  Bashkir: 0.09,
  Bengale: 0.09,
  'Belarus - Russian': 0.09,
  blen: 0.12,
  Burmese: 0.09,
  Bosnian: 0.09,
  Bravanese: 0.09,
  Bulgarian: 0.09,
  Bhutanese: 0.09,
  Cambodian: 0.09,
  Kananese: 0.09,
  Canjobal: 0.09,
  Cantonese: 0.09,
  Catalan: 0.09,
  Kashmir: 0.09,
  Kazakh: 0.09,
  Cebuano: 0.09,
  Chaldean: 0.09,
  Chamorro: 0.09,
  Chaozhou: 0.09,
  Chavacano: 0.09,
  'Chinese (Mandarin Traditional)': 0.09,
  Chona: 0.09,
  Chuquês: 0.09,
  Sinhalese: 0.09,
  Korean: 0.09,
  Cree: 0.09,
  Croatian: 0.09,
  Kurdo: 0.09,
  Curmânji: 0.09,
  Dakota: 0.09,
  Dari: 0.09,
  Dinka: 0.09,
  Dioula: 0.09,
  Slovak: 0.09,
  Slovenian: 0.09,
  Estonian: 0.09,
  Ewe: 0.09,
  Fanti: 0.09,
  Faroese: 0.09,
  Farsi: 0.09,
  Flamengo: 0.09,
  Frisian: 0.09,
  Fujian: 0.09,
  Fujianese: 0.09,
  Fula: 0.09,
  Fulani: 0.09,
  Fuzhou: 0.09,
  Gaélico: 0.09,
  Galego: 0.09,
  Galês: 0.09,
  Ganda: 0.09,
  Georgiano: 0.09,
  Gorani: 0.09,
  Guanxi: 0.09,
  Gujarati: 0.09,
  Hacá: 0.09,
  Haitiano: 0.09,
  Hassaniya: 0.09,
  Hauçá: 0.09,
  Hiligaynon: 0.09,
  Hindi: 0.09,
  'Hindi fijiano': 0.09,
  Hmong: 0.09,
  Húngaro: 0.09,
  Ibanag: 0.09,
  Igbo: 0.09,
  Iídiche: 0.09,
  Ilocano: 0.09,
  Ilonggo: 0.09,
  Indiano: 0.09,
  Indonésio: 0.09,
  Inuktitut: 0.09,
  Iorubá: 0.09,
  Irlandês: 0.09,
  Jakartanese: 0.09,
  Javanês: 0.09,
  Karen: 0.09,
  Khalkha: 0.09,
  Khmer: 0.09,
  Kikuyu: 0.09,
  Kirundi: 0.09,
  Kosovo: 0.09,
  Kotokoli: 0.09,
  Krio: 0.09,
  Lakota: 0.09,
  Laociano: 0.09,
  Latim: 0.09,
  Letão: 0.09,
  Lingala: 0.09,
  'Língua de sinais americana': 0.09,
  Lituano: 0.09,
  Luganda: 0.09,
  Luo: 0.09,
  Lusoga: 0.09,
  Luxemburguês: 0.09,
  Maay: 0.09,
  Macedônio: 0.09,
  Malaiala: 0.09,
  Malaio: 0.09,
  Maldivense: 0.09,
  Malgaxe: 0.09,
  Maltês: 0.09,
  'Mandarim Tradicional': 0.09,
  Mandinga: 0.09,
  Mandinka: 0.09,
  Maori: 0.09,
  Marata: 0.09,
  Marshalês: 0.09,
  Mien: 0.09,
  Mirpuri: 0.09,
  Mixteco: 0.09,
  Moldovan: 0.09,
  Mongol: 0.09,
  Napolitano: 0.09,
  Navajo: 0.09,
  Nepali: 0.09,
  Nianja: 0.09,
  Nuer: 0.09,
  Ojíbua: 0.09,
  Oriá: 0.09,
  Oromo: 0.10,
  Osseta: 0.09,
  Pachto: 0.09,
  Pahari: 0.09,
  Pampangan: 0.09,
  Patoá: 0.09,
  Pothwari: 0.09,
  Pulaar: 0.09,
  Punjabi: 0.09,
  Putian: 0.09,
  Quechua: 0.09,
  Quiniaruanda: 0.09,
  Quirguiz: 0.09,
  Romanche: 0.09,
  Romani: 0.09,
  Romeno: 0.09,
  Rundi: 0.09,
  Samoano: 0.09,
  Sango: 0.09,
  Sânscrito: 0.09,
  Sérvio: 0.09,
  Sichuan: 0.09,
  Siciliano: 0.09,
  Sindi: 0.09,
  Somali: 0.11,
  Soninquê: 0.09,
  Sorâni: 0.09,
  'Soto do sul': 0.09,
  Suaíle: 0.09,
  'Suázi / suazilandês': 0.09,
  Sundanês: 0.09,
  Susu: 0.09,
  Sylheti: 0.09,
  Tadjique: 0.09,
  Tagalog: 0.09,
  Tailandês: 0.09,
  Taiwanês: 0.09,
  Tâmil: 0.09,
  Telugu: 0.09,
  Tibetano: 0.09,
  Tigre: 0.12,
  Tigrinya: 0.09,
  Tonga: 0.09,
  Tshiluba: 0.09,
  Tsonga: 0.09,
  Tswana: 0.09,
  Turcomeno: 0.09,
  Ucraniano: 0.09,
  Uigur: 0.09,
  Uolofe: 0.09,
  Urdu: 0.09,
  Uzbeque: 0.09,
  Venda: 0.09,
  Vietnamita: 0.09,
  Visayan: 0.09,
  Xangainês: 0.09,
  Xhosa: 0.09,
  Yao: 0.09,
  Yupik: 0.09,
  Zulu: 0.09,

};

export const LANGUAGES = [
  'Spanish (ES)',
  'Spanish (LATAM)',
  'English US',
  'English UK',
  'Português BR',
  'Português PT',
  'Amharic',
  'French',
  'French Canadian',
  'Italian',
  'German',
  'Arabic',
  'Chinese (Mandarin Simplified)',
  'Danish',
  'Finnish',
  'Hebrew',
  'Dutch',
  'Icelandic',
  'Japanese',
  'Norwegian',
  'Russian',
  'Swedish',
  'Czech',
  'Turkish',
  'Polish',
  'Greek',
  'Afar',
  'Afrikaans',
  'Akan',
  'Albanian',
  'Agnwak',
  'Armenian',
  'Assamese',
  'Assyrian',
  'Azeri',
  'Bambara',
  'Basque',
  'Bashkir',
  'Bengale',
  'Belarus - Russian',
  'blen',
  'Burmese',
  'Bosnian',
  'Bravanese',
  'Bulgarian',
  'Bhutanese',
  'Cambodian',
  'Kananese',
  'Canjobal',
  'Cantonese',
  'Catalan',
  'Kashmir',
  'Kazakh',
  'Cebuano',
  'Chaldean',
  'Chamorro',
  'Chaozhou',
  'Chavacano',
  'Chinese (Mandarin Traditional)',
  'Chona',
  'Chuquês',
  'Sinhalese',
  'Korean',
  'Cree',
  'Croatian',
  'Kurdo',
  'Curmânji',
  'Dakota',
  'Dari',
  'Dinka',
  'Dioula',
  'Slovak',
  'Slovenian',
  'Estonian',
  'Ewe',
  'Fanti',
  'Faroese',
  'Farsi',
  'Flamengo',
  'Frisian',
  'Fujian',
  'Fujianese',
  'Fula',
  'Fulani',
  'Fuzhou',
  'Gaélico',
  'Galego',
  'Galês',
  'Ganda',
  'Georgiano',
  'Gorani',
  'Guanxi',
  'Gujarati',
  'Hacá',
  'Haitiano',
  'Hassaniya',
  'Hauçá',
  'Hiligaynon',
  'Hindi',
  'Hindi fijiano',
  'Hmong',
  'Húngaro',
  'Ibanag',
  'Igbo',
  'Iídiche',
  'Ilocano',
  'Ilonggo',
  'Indiano',
  'Indonésio',
  'Inuktitut',
  'Iorubá',
  'Irlandês',
  'Jakartanese',
  'Javanês',
  'Karen',
  'Khalkha',
  'Khmer',
  'Kikuyu',
  'Kirundi',
  'Kosovo',
  'Kotokoli',
  'Krio',
  'Lakota',
  'Laociano',
  'Latim',
  'Letão',
  'Lingala',
  'Língua de sinais americana',
  'Lituano',
  'Luganda',
  'Luo',
  'Lusoga',
  'Luxemburguês',
  'Maay',
  'Macedônio',
  'Malaiala',
  'Malaio',
  'Maldivense',
  'Malgaxe',
  'Maltês',
  'Mandarim Tradicional',
  'Mandinga',
  'Mandinka',
  'Maori',
  'Marata',
  'Marshalês',
  'Mien',
  'Mirpuri',
  'Mixteco',
  'Moldovan',
  'Mongol',
  'Napolitano',
  'Navajo',
  'Nepali',
  'Nianja',
  'Nuer',
  'Ojíbua',
  'Oriá',
  'Oromo',
  'Osseta',
  'Pachto',
  'Pahari',
  'Pampangan',
  'Patoá',
  'Pothwari',
  'Pulaar',
  'Punjabi',
  'Putian',
  'Quechua',
  'Quiniaruanda',
  'Quirguiz',
  'Romanche',
  'Romani',
  'Romeno',
  'Rundi',
  'Samoano',
  'Sango',
  'Sânscrito',
  'Sérvio',
  'Sichuan',
  'Siciliano',
  'Sindi',
  'Somali',
  'Soninquê',
  'Sorâni',
  'Soto do sul',
  'Suaíle',
  'Suázi / suazilandês',
  'Sundanês',
  'Susu',
  'Sylheti',
  'Tadjique',
  'Tagalog',
  'Tailandês',
  'Taiwanês',
  'Tâmil',
  'Telugu',
  'Tibetano',
  'Tigre',
  'Tigrinya',
  'Tonga',
  'Tshiluba',
  'Tsonga',
  'Tswana',
  'Turcomeno',
  'Ucraniano',
  'Uigur',
  'Uolofe',
  'Urdu',
  'Uzbeque',
  'Venda',
  'Vietnamita',
  'Visayan',
  'Xangainês',
  'Xhosa',
  'Yao',
  'Yupik',
  'Zulu',
];

